apiVersion: v1
kind: Service
metadata:
  name: celeb-matcher-service
  namespace: celeb
  labels:
    app: celeb-matcher
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30080
  selector:
    app: celeb-matcher