apiVersion: apps/v1
kind: Deployment
metadata:
    name: celeb-matcher # Name of the deployment.
    namespace: celeb
spec:
    selector:  # This specifies the selector, what pods to select in this deployment.
        matchLabels:  # We are saying select pods which matches labels
            app: celeb-matcher  # This is the label to match
    replicas: 1 # Number of replica pods to run.
    template: # Describes the pods that will be used for the deployment.
        metadata:
            labels: # Specifying the label of this pod, Here we are giving app : celeb-matcher which gets looked up by selector
                    # of the deployment section above
                app: celeb-matcher
        spec:
            containers: # List of containers running in each pod.
                - name: celeb-matcher
                  image: ishanbhatt/celebrity:latest  # repo/image:tag
                  imagePullPolicy: Always
